version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq

  nodejs:
    build: .
    container_name: node
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
    command: npm start